### ISSUE TITLE
Encabezado, nota al pie y paginación

### ISSUE THREAD

**Issue by argclc** [fideladorni/pase-barranitario#3]
Gracias! Es excelente!

Para mejorar aún más, se podría agregar el encabezado con el escudo nacional:

![image](https://user-images.githubusercontent.com/96701504/147419490-09709222-486c-423a-a69d-e1f2b242b09c.png)

Y en el pie de página una nota:

![image](https://user-images.githubusercontent.com/96701504/147419497-9734a5ac-9eb8-4c60-b59c-2af10c97c13c.png)

Por último, habría que separar un poco más las tarjetas cosa que la tercera salte a la segunda hoja.

**Comment by Manuel-777** [comment]
Tenes los token/url para ver el css? el mio se ve diferente con el logo y el texto arriba

**Comment by fideladorni** [comment]
Ahi lo agrego @Manuel-777 !
